version: "3.8"

services:
  nuxt_project:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/home/node"
    ports:
      - "8000:8000"

    # ↓ 次回起動後にコメントアウトを解除
    # volumes:
    #   - ./src:/src:cached
    # - exception_node_modules:/src/node_modules

    tty: true
    environment:
      - port=8000
      - DEVCONTAINER=true
      - CHOKIDAR_USEPOLLING=true
# ↓ 次回起動後にコメントアウトを解除
# volumes:
#   exception_node_modules:
