version: "3.8"

services:
  nuxt_project:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/home/node"
    ports:
      - "3000:3000"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - DEVCONTAINER=true
      - CHOKIDAR_USEPOLLING=true
