version: "3.8"

services:
  nuxt_project:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/home/node"
    ports:
      - "8000:8000"
    tty: true
    environment:
      - port=8000
      - DEVCONTAINER=true
      - CHOKIDAR_USEPOLLING=true
