version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./src:/src:cached
      # - node_modules:/src/node_modules
      # ↑ 次回起動後にコメントアウトを解除
    working_dir: "/src"
    ports:
      - "3000:3000"
    tty: true
    environment:
      - port=3000
      - CHOKIDAR_USEPOLLING=true
      - DEVCONTAINER=true

volumes:
  node_modules:
