version: "3.8"

services:
  nuxt_project:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: "/home/node"
    ports:
      - "80:3000"
      - "24678:24678"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=80
      - DEVCONTAINER=true
      - CHOKIDAR_USEPOLLING=true
